name: Refresh Token

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer petición a la API de Vercel
        run: curl -X GET https://rivoltaseguros.vercel.app/api/refreshToken
